### ISSUE TITLE
Test for perfect sql is unchanged, has no errors.

### ISSUE THREAD

**Issue by nolanbconaway** [sqlfluff/sqlfluff-online#22]
I almost merged a PR in which even perfect SQL had a no-newline-at-end-of-file error. That should have been caught in a test.

**Comment by tunetheweb** [comment]
What do you mean by this btw?

Are you complaining that this should flag a newline warning rather than automatically add a new line and pass?

![image](https://user-images.githubusercontent.com/10931297/130586113-d0ea323d-e340-4367-aa77-328b801bf1bc.png)

Cause it looks like that's intentional:

https://github.com/sqlfluff/sqlfluff-online/blob/a6cdc8fd203d1dc3f052324dfa514ca2b0b70437/src/app/routes.py#L41-L44

Easy enough to fix though by removing that last `\n`:

![image](https://user-images.githubusercontent.com/10931297/130586186-cd42f2bb-3905-4c32-a620-f4c4b6a0907e.png)

**Comment by nolanbconaway** [comment]
Oh! no! i want a test that the newline error is _not_ raised even when fluff might want to. My take is that pasting SQL is different than writing it in a file and we shouldn't enforce that rule. That being said, I haven't looked at the python API and it may be possible to simply disable the rule nowadays (so we needn't wrap the code like that)

**Comment by tunetheweb** [comment]
The code is there to do that already as a listed above. If you paste SQL with a trailing new line it will automatically add it. Try it on production!

Looks like you added it around the time you raised this issue 😁
https://github.com/sqlfluff/sqlfluff-online/commit/b7d1cca063648db1c417879d9816fca13bcae4d3

So is there anything further to do here?

**Comment by nolanbconaway** [comment]
Lo no, the issue is to write a _test_ that this behavior occurs! I implemented the fix when i pushed a bug but i never implemented a test for it!

**Comment by tunetheweb** [comment]
OK got you. Added three new asserts to #29 

https://github.com/sqlfluff/sqlfluff-online/blob/5e7055ab169ee0d32f0c6e32d2a1d6efd265ad8d/test/test_app.py#L71-L77

**Comment by nolanbconaway** [comment]
Perfect!
